# Default values for muffin-wallet-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 2

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: userviktoriuss/muffin-wallet
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.1.0

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80
  targetPort: 8081

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: muffin.example.com
      paths:
        - path: /
          pathType: Prefix


# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  enabled: true
  httpGet:
    path: /actuator/health/liveness
  initialDelaySeconds: 30
  periodSeconds: 5
readinessProbe:
  enabled: true
  httpGet:
    path: /actuator/health/readiness
  initialDelaySeconds: 5
  periodSeconds: 10


volume:
  name: application-config-volume

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: application-config-volume
    mountPath: /app/config


configMap:
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.containers.internal:5432/muffin_wallet"
  LOGGING_LEVEL_ROOT: "INFO"
  CURRENCY_SERVICE_URL: "http://muffin-currency:8083/rate"

secret:
  SPRING_DATASOURCE_USERNAME: "muffin-wallet"
  SPRING_DATASOURCE_PASSWORD: "muffin-wallet"