# Default values for muffin-currency-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 3

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: userviktoriuss/muffin-currency
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.0

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8083
  targetPort: 8080

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  enabled: true
  httpGet:
    path: /rate?from=PLAIN&to=CHOKOLATE
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  enabled: true
  httpGet:
    path: /rate?from=PLAIN&to=CHOKOLATE
  initialDelaySeconds: 2
  periodSeconds: 5


# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""
